const $=s=>document.querySelector(s);let state={threads:[],members:[],boards:[],tasks:[]};let current=1;let currentBoard=1;let lastMessageId=0;let activeAgent=null;let lastActivityId=0;let activityItems=new Map();let activityPolling=false;
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||`HTTP ${r.status}`);return x}
function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!=null)el.textContent=text;return el}
function clear(el){el.replaceChildren()}
function avatar(name){return node('span','avatar',name.slice(0,2).toUpperCase())}
function renderNav(){
  let groups=$('#threads'),dms=$('#dms');clear(groups);clear(dms);
  for(const t of state.threads){
    let b=node('button','item'+(t.id===current?' active':''));b.append(node('span','hash',t.kind==='dm'?'↗':'#'),node('span','',t.title));
    b.onclick=()=>{current=t.id;lastMessageId=0;renderNav();loadThread()};
    if(t.kind==='dm'){dms.append(b);continue}
    let row=node('div','thread-nav-row');let rename=node('button','rename-thread','✎');let del=node('button','delete-thread','×');
    rename.type='button';rename.title=`重命名群聊 ${t.title}`;rename.setAttribute('aria-label',rename.title);rename.onclick=()=>renameThread(t);
    del.type='button';del.title=`删除群聊 ${t.title}`;del.setAttribute('aria-label',del.title);del.onclick=()=>deleteThread(t);
    row.append(b,rename,del);groups.append(row);
  }
  let box=$('#members');clear(box);for(const m of state.members.filter(x=>x.name!=='human')){let row=node('div','member-nav');let b=node('button','item');b.append(avatar(m.name),node('span','',m.name),node('span','status '+(m.status==='busy'?' busy':''),m.status==='busy'?'忙':'闲'));b.title=`查看 ${m.name} 的工作流`;b.onclick=()=>openActivity(m.name);let dm=node('button','member-action','✉');dm.title=`与 ${m.name} 私聊`;dm.onclick=()=>openDm(m.name);let edit=node('button','edit-member','✎');edit.title=`编辑 ${m.name} 的身份和启动词`;edit.onclick=()=>editMember(m.name);row.append(b,dm,edit);box.append(row)}box=$('#boards');clear(box);for(const b of state.boards){let x=node('button','item'+(b.id===currentBoard?' active':''));x.append(node('span','hash','▦'),node('span','',b.title));x.onclick=()=>{currentBoard=b.id;renderNav();renderTasks()};box.append(x)}}
async function deleteThread(t){if(!confirm(`确定删除群聊「${t.title}」及其全部消息？此操作无法撤销。`))return;try{await api(`/api/threads/${t.id}/delete`,'POST',{});if(current===t.id){current=null;lastMessageId=0}await refresh()}catch(err){alert(err.message)}}
function renameThread(t){modal('重命名群聊',[{label:'群名',name:'title',value:t.title}],async f=>api(`/api/threads/${t.id}/rename`,'POST',{title:f.get('title')}))}
async function refresh(){let x=await api('/api/bootstrap');state={...state,...x};let t=await api('/api/tasks');state.tasks=t.tasks;if(!state.threads.some(t=>t.id===current)){current=state.threads[0]?.id||null;lastMessageId=0}renderNav();renderTasks();updateActivityStatus();await loadThread(false)}
async function loadThread(force=true){if(!current){$('#channel-title').textContent='选择一个群聊或私聊';$('#channel-subtitle').textContent='暂无讨论串';clear($('#messages'));clear($('#participants'));return}let x=await api(`/api/threads/${current}/messages`);$('#channel-title').textContent=x.thread.title;$('#channel-subtitle').textContent=`${x.members.length} 位成员 · ${x.thread.kind==='dm'?'私聊':'讨论串'} · thread-${current}`;let newest=x.messages.at(-1)?.id||0;if(force||newest!==lastMessageId){let box=$('#messages');let nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<100;clear(box);for(const m of x.messages){let row=node('div','message');row.append(avatar(m.sender));let content=node('div');let meta=node('div','meta');meta.append(node('strong','',m.sender),node('span','',m.created_at));content.append(meta,node('div','body',m.body));row.append(content);box.append(row)}if(!x.messages.length)box.append(node('div','empty','这里还没有消息。发第一句话吧。'));if(nearBottom||force)box.scrollTop=box.scrollHeight;lastMessageId=newest}let peers=$('#participants');clear(peers);for(const p of x.members){let m=state.members.find(y=>y.name===p.name);let row=node('div','member-line');row.append(avatar(p.name));let mid=node('span');mid.append(node('strong','',p.name),node('small','',p.mode==='observer'?'旁听者':'参与者'));row.append(mid);if(m&&p.name!=='human')row.append(node('span','status '+(m.status==='busy'?'busy':''),m.status==='busy'?'忙着':'闲着'));peers.append(row)}}
function renderTasks(){let box=$('#tasks');clear(box);let tasks=state.tasks.filter(t=>t.board_id===currentBoard);for(const t of tasks.slice(0,12)){let row=node('div','task');row.append(node('span','badge',`TASK-${t.id} · ${t.status}`),node('div','',t.title),node('small','',`负责人：${t.assignee||'未分派'}`),node('small','',`提醒：${t.remind_at||'无'}`));box.append(row)}if(!tasks.length)box.append(node('div','empty','还没有任务'))}
function modal(title,fields,onSave){$('#modal-title').textContent=title;let box=$('#modal-fields');clear(box);for(const f of fields){let label=node('label','',f.label);if(f.type==='members'){for(const m of state.members.filter(x=>x.name!=='human')){let c=node('label','check');let input=node('input');input.type='checkbox';input.value=m.name;input.name='members';c.append(input,node('span','',m.name));box.append(c)}continue}let input=f.type==='select'?node('select'):f.type==='textarea'?node('textarea'):node('input');input.name=f.name;if(f.type==='select'){for(const [value,text] of f.options){let o=node('option','',text);o.value=value;input.append(o)}}else if(f.type!=='textarea')input.type=f.type==='datetime-local'?'datetime-local':'text';input.value=f.value||'';input.placeholder=f.placeholder||'';label.append(input);box.append(label)}$('#modal').showModal();$('#modal-form').onsubmit=async e=>{e.preventDefault();let form=e.target;try{await onSave(new FormData(form));$('#modal').close();form.reset();await refresh()}catch(err){alert(err.message)}}}
async function editMember(name){let m=await api(`/api/members/${name}`);modal(`编辑 ${name} 的设定`,[{label:'对外公开身份',type:'textarea',name:'public_md',value:m.public_md},{label:'日常启动词（仅该 Agent 可见）',type:'textarea',name:'role_md',value:m.role_md},{label:'八小时巡查词（仅该 Agent 可见）',type:'textarea',name:'patrol_md',value:m.patrol_md}],async f=>api(`/api/members/${name}`,'POST',{public_md:f.get('public_md'),role_md:f.get('role_md'),patrol_md:f.get('patrol_md')}))}
function updateActivityStatus(){if(!activeAgent)return;let member=state.members.find(m=>m.name===activeAgent);$('#activity-status').textContent=member?.status==='busy'?'忙着 · 实时更新':'闲着 · 最近工作记录'}
function addActivity(events){let feed=$('#activity-feed');let nearBottom=feed.scrollHeight-feed.scrollTop-feed.clientHeight<100;if(events.length&&feed.firstElementChild?.classList.contains('empty'))clear(feed);for(const event of events){lastActivityId=Math.max(lastActivityId,event.id);let key=event.item_id?`item:${event.item_id}`:`event:${event.id}`;let entry=activityItems.get(key);if(!entry){let card=node('article','activity-item '+event.kind);let meta=node('div','activity-meta');let title=node('strong','',event.title||event.kind);let stamp=node('span','',new Date(event.created_at).toLocaleTimeString());meta.append(title,stamp);let body=node('pre','activity-text');card.append(meta,body);feed.append(card);entry={card,title,body};activityItems.set(key,entry)}if(event.title)entry.title.textContent=event.title;if(event.phase==='delta')entry.body.textContent+=event.text||'';else if(event.text)entry.body.textContent=event.text;entry.card.dataset.phase=event.phase;while(feed.children.length>120){let first=feed.firstElementChild;for(const [k,v] of activityItems)if(v.card===first){activityItems.delete(k);break}first.remove()}}if(nearBottom)feed.scrollTop=feed.scrollHeight;if(!events.length&&!feed.children.length)feed.append(node('p','empty','还没有工作记录。新一轮 Codex 工作开始后会在这里显示。'))}
async function pollActivity(initial=false){if(activityPolling||!activeAgent||!$('#activity-dialog').open)return;activityPolling=true;let name=activeAgent;try{let path=`/api/agents/${name}/activity?${initial?'limit=200':`after=${lastActivityId}`}`;let result=await api(path);if(activeAgent!==name)return;if(initial)clear($('#activity-feed'));addActivity(result.events);updateActivityStatus()}finally{activityPolling=false}}
async function openActivity(name){activeAgent=name;lastActivityId=0;activityItems=new Map();$('#activity-title').textContent=`${name} 的 Codex 工作流`;clear($('#activity-feed'));updateActivityStatus();$('#activity-dialog').showModal();try{await pollActivity(true)}catch(error){$('#activity-feed').textContent=error.message}}
$('#activity-close').onclick=()=>$('#activity-dialog').close();$('#activity-dialog').onclose=()=>{activeAgent=null;activityItems=new Map()};$('#activity-dm').onclick=async()=>{let name=activeAgent;$('#activity-dialog').close();if(name)await openDm(name)};
setInterval(()=>{if(activeAgent)pollActivity().catch(console.error)},1200);
async function openDm(name){let old=state.threads.find(t=>t.kind==='dm'&&t.title===`与 ${name} 私聊`);if(old){current=old.id;renderNav();await loadThread();return}let x=await api('/api/threads','POST',{title:`与 ${name} 私聊`,members:[name],kind:'dm'});current=x.id;await refresh()}
$('#new-thread').onclick=()=>modal('创建讨论串',[{label:'群名',name:'title',placeholder:'例如：越南语项目'},{label:'邀请成员',type:'members'}],async f=>{let x=await api('/api/threads','POST',{title:f.get('title'),members:f.getAll('members')});current=x.id});
$('#new-board').onclick=()=>modal('创建看板',[{label:'看板名称',name:'title'}],async f=>{let x=await api('/api/boards','POST',{title:f.get('title')});currentBoard=x.id});
$('#new-task').onclick=()=>modal('创建任务',[{label:'任务标题',name:'title'},{label:'任务描述',name:'description'},{label:'负责人',type:'select',name:'assignee',options:[['','未分派'],...state.members.filter(x=>x.name!=='human').map(x=>[x.name,x.name])]},{label:'提醒时间（留空则 30 分钟后）',type:'datetime-local',name:'remind_at'}],async f=>api('/api/tasks','POST',{board_id:currentBoard,title:f.get('title'),description:f.get('description'),assignee:f.get('assignee')||null,remind_at:f.get('remind_at')?new Date(f.get('remind_at')).toISOString():null}));
$('#cancel').onclick=()=>$('#modal').close();$('#message-form').onsubmit=async e=>{e.preventDefault();let input=$('#message-input'),body=input.value.trim();if(!body)return;try{await api(`/api/threads/${current}/messages`,'POST',{body});input.value='';await loadThread()}catch(err){alert(err.message)}};
$('#message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#message-form').requestSubmit()}};
refresh().catch(e=>alert(e.message));setInterval(()=>refresh().catch(console.error),2500);
